### ISSUE TITLE
Not working out of the box in Laravel 4.2

### ISSUE THREAD

**Issue by DmitryVarennikov** [YOzaz/Laravel-SwiftMailer#3]
This solution doesn't work out of the box. When queueing emails the handler is `mailer@handleQueuedMessage` which resolves into `Illuminate\Mail\Mailer@handleQueuedMessage` as we don't replace `mailer` in the DI container. 

And even if I explicitly call `Queue::push` with `laravel-swiftmailer.mailer@handleQueuedMessage` `YOzaz\LaravelSwiftmailer\Mailer` doesn't intercept it and passes payload to the `Illuminate\Mail\Mailer` 

UPD: I use Laravel 4.2

**Comment by YOzaz** [comment]
Hi @dVaffection , and thanks for bug report!
Unfortunately, I'm really busy at the moment and won't have a chance to look into it. Would you mind creating a pull request with bug fixed?

**Comment by YOzaz** [comment]
OK, it looks like using Queue methods may require one of the following:
- Intercept all Queue methods and replace queue handler with custom, or
- Build custom Queue wrapper which would call package auto-reset before executing a job.

Honestly, not sure if this is actual for the moment, but will build a patch if it will get more attention here.

**Comment by YOzaz** [comment]
Fixed with [v3.2.0](https://github.com/YOzaz/Laravel-SwiftMailer/releases/tag/v3.2.0). Please come back for any issues, as it was quite tough to compare sources amongst different Laravel source trees :smiley:.

This is a last release, as Laravel 5.0 already forces reconnection on every message. See [here](https://github.com/laravel/framework/commit/af8eb1face000f82e5c85e6eb822075fc313cbb9).
